version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
    - rabbitmq_data:/rabbitmq/data
    - rabbitmq_log:/rabbitmq/log
    - ./rabbitmq_config:/rabbitmq/config
    
  server:
    build: ./server
    depends_on:
      - rabbitmq
    environment:
      - RBMQ_BROKER=rabbitmq
  
  client:
    build: ./client
    depends_on:
      - server
      - rabbitmq
    environment:
      - RBMQ_BROKER=rabbitmq
    volumes:
      - ./data/:/app/data/

volumes:
  rabbitmq_data:
  rabbitmq_log:
